stages:
  - build

variables:
  LC_ALL: "en_US.UTF-8" # apparently xcpretty won't function correctly otherwise

before_script:
  - pod deintegrate
  - pod install

build_project:
  stage: build
  script:
    - xcodebuild clean -workspace EcoTravel.xcworkspace -scheme EcoTravel | xcpretty
    - xcodebuild test -workspace EcoTravel.xcworkspace -scheme EcoTravel -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.4' | xcpretty -s
  tags:
    - EcoTravel