stages:
  - build

build_project:
  stage: build
  script:
    - xcodebuild clean -project EcoTravel.xcodeproj -scheme EcoTravel | xcpretty
    - xcodebuild test -project EcoTravel.xcodeproj -scheme EcoTravel -destination 'platform=iOS Simulator,name=iPhone 11,OS=14.4' | xcpretty -s
  tags:
    - Tuomas
